name: Build on Push

on:
  push:
    branches:
      - main  # Adjust this if you want to trigger the workflow on other branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Create a ZIP archive with the contents of the root directory
    - name: Zip the contents
      run: |
        zip -r repo-main.zip . -x .git/\* .github/\*

    # Step 3: Upload the ZIP file as a build artifact (optional)
    - name: Upload the zip
      uses: actions/upload-artifact@v3
      with:
        name: pack
        path: pack.zip
