name: Build on Push

on:
  push:
    branches:
      - main  # Adjust this if you want to trigger the workflow on other branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Upload the folder as a build artifact
    - name: Upload the zip
      uses: actions/upload-artifact@v4
      with:
        name: pack
        path: .

    - name: Create Release
      uses: actions/github-script@v6
      with:
        script: |
          const response = await github.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `release-${Date.now()}`, // Create a unique tag name using a timestamp
            name: `Release ${new Date().toISOString()}`, // Release name with a timestamp
            body: 'Description of the release', // Description of the release
            draft: false,
            prerelease: false
          });
          return response.data;

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # Upload URL from the created release
        asset_path: pack.zip
        asset_name: pack.zip
        asset_content_type: application/zip
